version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/mydatabase
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
