jobs:
  job1:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Bafana1992
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    env:
      database_hostname: "localhost"
      database_port: "5432"
      database_username: "postgres"
      database_password: "Bafana1992"
      database_name: "fastapi"
      secret_key: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      algorithm: "HS256"
      access_token_expire_minutes: "30"
      database_url: "postgresql://postgres:Bafana1992@localhost:5432/test_db"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python version 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install httpx
        run: pip install httpx

      - name: Create test database
        run: |
          sudo apt-get install postgresql-client
          psql -h localhost -U postgres -c "CREATE DATABASE fastapi_test;"

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest
