name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}  # From GitHub Secrets
      DATABASE_NAME: fastapi_test
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 300
      DATABASE_URL: postgresql://postgres:${{ secrets.DATABASE_PASSWORD }}@postgres:5432/fastapi_test

    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increase the timeout

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: fastapi_test
        ports:
          - 5433:5432  # Use different host port to avoid conflicts
        options: >-
          --network my_network
          --cpus="1"
          --memory="1g"
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Create Docker network
        run: docker network create my_network

      - name: Pulling git repo
        uses: actions/checkout@v3

      - name: Pull PostgreSQL image
        run: docker pull postgres:13

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python version 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install all dependencies
        run: pip install -r requirements.txt

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Set up PostgreSQL password file
        run: |
          echo "postgres:5432:*:postgres:${{ secrets.DATABASE_PASSWORD }}" > ~/.pgpass
          chmod 0600 ~/.pgpass

      - name: Create fastapi_test database
        run: |
          until pg_isready -h postgres -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 3
          done
          psql -h postgres -U postgres -c "CREATE DATABASE ${DATABASE_NAME};"

      - name: Test with pytest
        run: |
          pip install pytest
          pytest --disable-warnings -q

      - name: Display PostgreSQL container logs
        run: docker logs $(docker ps -a -q --filter "name=postgres")

      - name: Check PostgreSQL status
        run: docker ps -a
